version: '3.4'

services:
  
    petalaka.account.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        ports:
         - "8080:8080"
    
    petalaka.apigateway:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        ports:
        - "5000:8080"

    petalaka.email.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        ports:
        - "8082:8080"
    petalaka.petstore.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        ports:
        - "8083:8080"