version: '3.4'

services:
  
    petalaka.account.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/sharedCert.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
        ports:
         - "8080:8081"
        volumes:
         - ./usersecrets:/home/app/.microsoft/usersecrets:ro
         - ./https:/home/app/.aspnet/https:ro

    petalaka.apigateway:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/sharedCert.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
        ports:
        - "5000:8081"
        volumes:
         - ./usersecrets:/home/app/.microsoft/usersecrets:ro
         - ./https:/home/app/.aspnet/https:ro

    petalaka.email.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/sharedCert.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
        ports:
        - "8082:8081"
        volumes:
         - ./usersecrets:/home/app/.microsoft/usersecrets:ro
         - ./https:/home/app/.aspnet/https:ro

    petalaka.petstore.api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/sharedCert.pfx
        - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
        ports:
        - "8083:8081"
        volumes:
         - ./usersecrets:/home/app/.microsoft/usersecrets:ro
         - ./https:/home/app/.aspnet/https:ro

    petalaka.payment.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/sharedCert.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
        ports:
            - "8084:8081"
        volumes:
         - ./usersecrets:/home/app/.microsoft/usersecrets:ro
         - ./https:/home/app/.aspnet/https:ro